al_activity.bin: al_activity.c arraylist.h arraylist.c
	gcc -ggdb al_activity.c arraylist.c -o al_activity.bin

al_activity_solution.bin: al_activity_solution.c arraylist.h arraylist.c
	gcc -ggdb al_activity_solution.c arraylist.c -o al_activity_solution.bin

clean:
	rm -f *.bin
