all: shell hibernate ping

#################################
# PLEASE DO NOT DELETE THIS LINE
LDLIBS = -lreadline
#################################

.PHONY: all clean

clean:
	rm -f *.o shell hibernate ping
